export const API_REQUESTS = {
  nowPlaying: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/movie/now_playing`,
  popular: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/movie/popular`,
  topUpcoming: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/movie/upcoming`,
  topRated: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/movie/top_rated`,
  trending: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/trending/all/day`,
  sciFi: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=878`,
  war: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=10752`,
  crime: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=80`,
  animation: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=16`,
  horror: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=27`,
  comedy: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=35`,
  adventure: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=12`,
  drama: `${process.env.NEXT_PUBLIC_TMDB_API_URL}/3/discover/movie?with_genres=18`,
};
